import type { LevelData, TimelineVisualState } from '../types';

const gone: TimelineVisualState = { solid: false, visible: false, color: 0x000000, alpha: 0 };
const pastSolid: TimelineVisualState = { solid: true, visible: true, color: 0x8d6b42 };
const presentSolid: TimelineVisualState = { solid: true, visible: true, color: 0x263743 };
const futureSolid: TimelineVisualState = { solid: true, visible: true, color: 0x3d2a35 };
const brokenPresent: TimelineVisualState = { solid: false, visible: true, color: 0x33414a, alpha: 0.32 };
const overgrown: TimelineVisualState = { solid: true, visible: true, color: 0x426b48 };
const ruinedGhost: TimelineVisualState = { solid: false, visible: true, color: 0x522b33, alpha: 0.36 };

export const levels: LevelData[] = [
  {
    id: 'tutorial',
    title: 'The Folded Reactor',
    subtitle: 'Beneath the dead heart of the city.',
    width: 1850,
    height: 720,
    spawn: { x: 90, y: 600 },
    objective: 'Find a way through the first fracture.',
    nextLevelId: 'level-1',
    startTimeline: 'present',
    background: 'reactor',
    startLines: [
      'The clock above Elias has stopped. The thing in his chest has not.',
      'Q bends the hour. 1, 2, 3 force it: Past, Present, Future.',
    ],
    platforms: [
      { id: 'reactor-floor-left', x: 430, y: 690, width: 860, height: 60 },
      { id: 'reactor-floor-right', x: 1400, y: 690, width: 900, height: 60 },
      { id: 'reactor-step', x: 505, y: 590, width: 180, height: 24, color: 0x2d3c43 },
    ],
    timelineBlocks: [
      {
        id: 'remembered-bridge',
        x: 965,
        y: 635,
        width: 230,
        height: 24,
        states: {
          past: pastSolid,
          present: brokenPresent,
          future: gone,
        },
      },
      {
        id: 'rusted-service-gate',
        x: 1590,
        y: 610,
        width: 54,
        height: 102,
        states: {
          past: { solid: true, visible: true, color: 0x6a573d },
          present: { solid: true, visible: true, color: 0x40505a },
          future: { solid: false, visible: true, color: 0x73313a, alpha: 0.25 },
        },
      },
    ],
    doors: [],
    plates: [],
    switches: [],
    enemies: [],
    checkpoints: [{ id: 'reactor-checkpoint', x: 760, y: 620 }],
    storyZones: [
      {
        id: 'timeline-hint',
        x: 785,
        y: 600,
        width: 110,
        height: 140,
        once: true,
        lines: ['The bridge exists in another hour.'],
      },
      {
        id: 'future-hint',
        x: 1420,
        y: 600,
        width: 120,
        height: 140,
        once: true,
        lines: ['The gate survives the present. Not the future.'],
      },
    ],
    memoryFragments: [
      {
        id: 'reactor-daughter-sketch',
        title: 'Memory Fragment: Folded Paper',
        x: 555,
        y: 548,
        lines: ['A child drew the city with three suns. Elias remembers laughing before the Core learned how to stop.'],
      },
    ],
    exit: { x: 1760, y: 600, width: 70, height: 130 },
  },
  {
    id: 'level-1',
    title: 'Lock Street',
    subtitle: 'Rain hangs over a city that refuses to move.',
    width: 2050,
    height: 720,
    spawn: { x: 90, y: 600 },
    objective: 'Leave an echo behind. Walk through what it opens.',
    nextLevelId: 'rain-crossing',
    startTimeline: 'present',
    background: 'streets',
    startLines: [
      'Outside, the city is holding its breath. Even the rain has forgotten how to fall.',
      'Something watches from the roofs. It moves when the rest of the world does not.',
    ],
    platforms: [
      { id: 'street-left', x: 400, y: 690, width: 800, height: 60 },
      { id: 'street-right', x: 1525, y: 690, width: 1050, height: 60 },
      { id: 'street-awning', x: 690, y: 560, width: 190, height: 22, color: 0x273844 },
    ],
    timelineBlocks: [
      {
        id: 'old-street-bridge',
        x: 910,
        y: 635,
        width: 260,
        height: 24,
        states: {
          past: pastSolid,
          present: brokenPresent,
          future: gone,
        },
      },
    ],
    doors: [
      {
        id: 'plate-door',
        x: 1160,
        y: 610,
        width: 54,
        height: 102,
        requiresFlags: ['street_plate'],
        states: {
          past: { solid: true, visible: true, color: 0x75614d },
          present: { solid: true, visible: true, color: 0x32434f },
          future: { solid: true, visible: true, color: 0x57333b },
        },
      },
    ],
    plates: [{ id: 'street-pressure-plate', flag: 'street_plate', x: 420, y: 656, width: 82, height: 12 }],
    switches: [],
    enemies: [{ id: 'first-rustmite', x: 1480, y: 620, patrolMinX: 1310, patrolMaxX: 1690, speed: 68 }],
    checkpoints: [{ id: 'street-checkpoint', x: 1320, y: 620 }],
    storyZones: [
      {
        id: 'echo-hint',
        x: 340,
        y: 600,
        width: 130,
        height: 140,
        once: true,
        lines: ['Record. Leave. Let the echo stay behind.'],
      },
      {
        id: 'keeper-trace',
        x: 1560,
        y: 600,
        width: 120,
        height: 140,
        once: true,
        lines: ['A black shape blinks between raindrops. The roofs are not empty.'],
      },
    ],
    memoryFragments: [
      {
        id: 'rain-payphone',
        title: 'Memory Fragment: Last Call',
        x: 705,
        y: 520,
        lines: ['The receiver is warm in the Past. In every other hour, the line is only rain.'],
      },
    ],
    exit: { x: 1950, y: 600, width: 70, height: 130 },
  },
  {
    id: 'rain-crossing',
    title: 'Rain District Crossing',
    subtitle: 'A black street where the lamps remember different storms.',
    width: 2320,
    height: 720,
    spawn: { x: 90, y: 600 },
    objective: 'Hold the old street open. Cross through the ruined hour.',
    nextLevelId: 'level-2',
    startTimeline: 'present',
    background: 'streets',
    startLines: [
      'Rain District teaches in repetitions. Elias leaves one version of himself behind and walks as another.',
      'The street only opens when the Past is held and the Future is trusted.',
    ],
    platforms: [
      { id: 'rain-crossing-left', x: 460, y: 690, width: 920, height: 60 },
      { id: 'rain-crossing-center', x: 1370, y: 690, width: 520, height: 60 },
      { id: 'rain-crossing-right', x: 2050, y: 690, width: 540, height: 60 },
      { id: 'rain-crossing-awning', x: 650, y: 560, width: 180, height: 22, color: 0x273844 },
    ],
    timelineBlocks: [
      {
        id: 'past-sign-bridge',
        x: 900,
        y: 610,
        width: 240,
        height: 22,
        states: {
          past: pastSolid,
          present: brokenPresent,
          future: gone,
        },
      },
      {
        id: 'future-drain-span',
        x: 1590,
        y: 600,
        width: 250,
        height: 22,
        states: {
          past: gone,
          present: ruinedGhost,
          future: futureSolid,
        },
      },
    ],
    doors: [
      {
        id: 'rain-memory-gate',
        x: 1220,
        y: 610,
        width: 54,
        height: 102,
        requiresFlags: ['rain_plate'],
        states: {
          past: { solid: true, visible: true, color: 0x75614d },
          present: { solid: true, visible: true, color: 0x32434f },
          future: { solid: true, visible: true, color: 0x57333b },
        },
      },
    ],
    plates: [{ id: 'rain-memory-plate', flag: 'rain_plate', x: 405, y: 656, width: 86, height: 12, timelines: ['past'] }],
    switches: [],
    enemies: [{ id: 'rain-rustmite', x: 1670, y: 620, patrolMinX: 1480, patrolMaxX: 1850, speed: 78 }],
    checkpoints: [{ id: 'rain-crossing-checkpoint', x: 1325, y: 620 }],
    storyZones: [
      {
        id: 'rain-echo-lesson',
        x: 360,
        y: 600,
        width: 150,
        height: 140,
        once: true,
        lines: ['The plate listens only to the Past. An echo can keep listening after Elias leaves.'],
      },
      {
        id: 'rain-future-lesson',
        x: 1540,
        y: 600,
        width: 160,
        height: 140,
        once: true,
        lines: ['The future is not safe. It is only honest about what has already broken.'],
      },
    ],
    memoryFragments: [
      {
        id: 'rain-lamp-letter',
        title: 'Memory Fragment: Letter Under Glass',
        x: 650,
        y: 520,
        lines: ['The ink has run, but one sentence remains: do not make grief into a machine.'],
      },
    ],
    exit: { x: 2240, y: 600, width: 70, height: 130 },
  },
  {
    id: 'level-2',
    title: 'Glasshouse Station',
    subtitle: 'Where steel rusts and roots remember.',
    width: 2240,
    height: 720,
    spawn: { x: 95, y: 600 },
    objective: 'Wake the route. Shift the hour. Keep moving.',
    nextLevelId: 'level-3',
    startTimeline: 'present',
    background: 'greenhouse',
    startLines: [
      'The station lives in pieces. In one hour, it blooms. In another, it dies.',
      'A girl stands where no one should be standing. "He thinks stillness is mercy," she says.',
    ],
    platforms: [
      { id: 'greenhouse-left', x: 520, y: 690, width: 1040, height: 60 },
      { id: 'greenhouse-middle', x: 1260, y: 690, width: 250, height: 60 },
      { id: 'greenhouse-right', x: 1810, y: 690, width: 860, height: 60 },
      { id: 'greenhouse-roof', x: 520, y: 520, width: 190, height: 24, color: 0x344647 },
    ],
    timelineBlocks: [
      {
        id: 'present-service-lift',
        x: 1085,
        y: 585,
        width: 160,
        height: 22,
        states: {
          past: { solid: false, visible: true, color: 0x3b6a42, alpha: 0.35 },
          present: presentSolid,
          future: gone,
        },
      },
      {
        id: 'future-catwalk',
        x: 1345,
        y: 535,
        width: 200,
        height: 22,
        states: {
          past: gone,
          present: ruinedGhost,
          future: futureSolid,
        },
      },
    ],
    doors: [
      {
        id: 'station-door',
        x: 1515,
        y: 610,
        width: 54,
        height: 102,
        requiresFlags: ['station_switch'],
        states: {
          past: { solid: true, visible: true, color: 0x4e6a45 },
          present: { solid: true, visible: true, color: 0x394b56 },
          future: { solid: true, visible: true, color: 0x5a2d3d },
        },
      },
    ],
    plates: [],
    switches: [{ id: 'station-switch', flag: 'station_switch', x: 655, y: 644, width: 42, height: 34 }],
    enemies: [{ id: 'greenhouse-rustmite', x: 1810, y: 620, patrolMinX: 1650, patrolMaxX: 2020, speed: 75 }],
    checkpoints: [{ id: 'greenhouse-checkpoint', x: 1580, y: 620 }],
    storyZones: [
      {
        id: 'girl-vanish',
        x: 470,
        y: 600,
        width: 140,
        height: 140,
        once: true,
        lines: ['The girl is gone when Elias blinks. Her footprints point in three directions.'],
      },
      {
        id: 'switch-echo',
        x: 610,
        y: 600,
        width: 150,
        height: 140,
        once: true,
        lines: ['Some choices must be made twice.'],
      },
    ],
    exit: { x: 2140, y: 600, width: 70, height: 130 },
  },
  {
    id: 'level-3',
    title: 'Platform 13',
    subtitle: 'A station assembled from incompatible years.',
    width: 2440,
    height: 720,
    spawn: { x: 95, y: 600 },
    objective: 'Force time to disagree with itself.',
    nextLevelId: 'bellweather-canals',
    startTimeline: 'present',
    background: 'station',
    startLines: [
      'The Keeper leaves messages where glass used to be: no change, no pain, no future.',
      'Elias can feel the lie in it. And the temptation.',
    ],
    platforms: [
      { id: 'station-left', x: 470, y: 690, width: 940, height: 60 },
      { id: 'station-center', x: 1470, y: 690, width: 820, height: 60 },
      { id: 'station-right', x: 2200, y: 690, width: 440, height: 60 },
      { id: 'station-roof', x: 720, y: 510, width: 170, height: 22, color: 0x38434a },
    ],
    timelineBlocks: [
      {
        id: 'past-ticket-bridge',
        x: 965,
        y: 605,
        width: 250,
        height: 22,
        states: {
          past: overgrown,
          present: brokenPresent,
          future: gone,
        },
      },
      {
        id: 'present-generator-lift',
        x: 1220,
        y: 520,
        width: 190,
        height: 22,
        states: {
          past: gone,
          present: presentSolid,
          future: ruinedGhost,
        },
      },
      {
        id: 'future-collapsed-span',
        x: 1445,
        y: 585,
        width: 220,
        height: 22,
        states: {
          past: gone,
          present: brokenPresent,
          future: futureSolid,
        },
      },
    ],
    doors: [
      {
        id: 'platform-lock',
        x: 1860,
        y: 610,
        width: 54,
        height: 102,
        requiresFlags: ['platform_switch'],
        states: {
          past: { solid: true, visible: true, color: 0x5f6542 },
          present: { solid: true, visible: true, color: 0x334553 },
          future: { solid: false, visible: true, color: 0x66313c, alpha: 0.28 },
        },
      },
    ],
    plates: [],
    switches: [{ id: 'platform-switch', flag: 'platform_switch', x: 1595, y: 644, width: 42, height: 34, timelines: ['future'] }],
    enemies: [
      { id: 'station-rustmite-a', x: 1420, y: 620, patrolMinX: 1290, patrolMaxX: 1580, speed: 80 },
      { id: 'station-rustmite-b', x: 2150, y: 620, patrolMinX: 1990, patrolMaxX: 2300, speed: 86 },
    ],
    checkpoints: [{ id: 'platform-checkpoint', x: 1260, y: 490 }],
    storyZones: [
      {
        id: 'keeper-message',
        x: 1780,
        y: 600,
        width: 150,
        height: 140,
        once: true,
        lines: ['The switch only exists in the ruined future. The Keeper whispers: "If time moves, it takes everything."'],
      },
    ],
    exit: { x: 2360, y: 600, width: 70, height: 130 },
  },
  {
    id: 'bellweather-canals',
    title: 'Bellweather Canals',
    subtitle: 'Floodgates below the city remember which hour drowned first.',
    width: 2620,
    height: 720,
    spawn: { x: 95, y: 600 },
    objective: 'Drain the canal in the Past. Cross the exposed future culvert.',
    nextLevelId: 'boss',
    startTimeline: 'present',
    background: 'canals',
    startLines: [
      'Bellweather is all black water and brass gates. The Past still has maintenance paths. The Future has exposed bones.',
      'The canal is deepest in the Present. Step wrong, and the hour takes Elias under.',
    ],
    platforms: [
      { id: 'canal-left-bank', x: 360, y: 690, width: 720, height: 60 },
      { id: 'canal-pump-house', x: 1180, y: 690, width: 360, height: 60 },
      { id: 'canal-right-bank', x: 2055, y: 690, width: 1030, height: 60 },
      { id: 'canal-maintenance-awning', x: 590, y: 545, width: 180, height: 22, color: 0x273844 },
      { id: 'canal-overlook', x: 1770, y: 535, width: 210, height: 22, color: 0x263743 },
    ],
    timelineBlocks: [
      {
        id: 'past-drain-ledge',
        x: 850,
        y: 610,
        width: 230,
        height: 22,
        states: {
          past: pastSolid,
          present: brokenPresent,
          future: gone,
        },
      },
      {
        id: 'future-culvert-span',
        x: 1470,
        y: 600,
        width: 260,
        height: 22,
        states: {
          past: gone,
          present: ruinedGhost,
          future: futureSolid,
        },
      },
      {
        id: 'past-service-sign',
        x: 1830,
        y: 590,
        width: 190,
        height: 22,
        states: {
          past: pastSolid,
          present: brokenPresent,
          future: gone,
        },
      },
    ],
    doors: [
      {
        id: 'canal-floodgate',
        x: 1320,
        y: 610,
        width: 54,
        height: 102,
        requiresFlags: ['canal_drain'],
        states: {
          past: { solid: true, visible: true, color: 0x75614d },
          present: { solid: true, visible: true, color: 0x32434f },
          future: { solid: true, visible: true, color: 0x57333b },
        },
      },
    ],
    plates: [{ id: 'canal-drain-plate', flag: 'canal_drain', x: 440, y: 656, width: 86, height: 12, timelines: ['past'] }],
    switches: [],
    enemies: [{ id: 'canal-rustmite', x: 2050, y: 620, patrolMinX: 1880, patrolMaxX: 2300, speed: 84 }],
    hazards: [
      {
        id: 'present-canal-water',
        x: 850,
        y: 674,
        width: 250,
        height: 42,
        timelines: ['present'],
        message: 'The present canal pulls Elias under.',
      },
      {
        id: 'future-black-drain',
        x: 1575,
        y: 674,
        width: 330,
        height: 42,
        timelines: ['past', 'present'],
        message: 'The flooded drain folds back to the last checkpoint.',
      },
    ],
    checkpoints: [{ id: 'canal-checkpoint', x: 1740, y: 620 }],
    storyZones: [
      {
        id: 'canal-drain-lesson',
        x: 390,
        y: 600,
        width: 150,
        height: 140,
        once: true,
        lines: ['The drain listens to the Past. Leave an echo with the old machinery, then move through what the Future exposes.'],
      },
      {
        id: 'canal-keeper-mark',
        x: 1960,
        y: 600,
        width: 160,
        height: 140,
        once: true,
        lines: ['Someone painted a clock face under the bridge. Every hand points down into the water.'],
      },
    ],
    memoryFragments: [
      {
        id: 'canal-bell-token',
        title: 'Memory Fragment: Brass Bell Token',
        x: 585,
        y: 505,
        lines: ['The token is stamped with Bellweather Transit. In the Past, children used it to cross the canal before the city learned to sink.'],
      },
    ],
    exit: { x: 2525, y: 600, width: 70, height: 130 },
  },
  {
    id: 'boss',
    title: 'The Still Hour',
    subtitle: 'At the center, time kneels.',
    width: 2520,
    height: 720,
    spawn: { x: 95, y: 600 },
    objective: 'Break the three anchors. Reach the Keeper.',
    startTimeline: 'present',
    background: 'core',
    startLines: [
      'Every broken hour in the city points here.',
      'The Keeper steps forward wearing Elias\'s face. "I did the only merciful thing," he says. "I stopped goodbye."',
    ],
    platforms: [
      { id: 'core-left', x: 470, y: 690, width: 940, height: 60 },
      { id: 'core-middle', x: 1420, y: 690, width: 760, height: 60 },
      { id: 'core-right', x: 2220, y: 690, width: 600, height: 60 },
      { id: 'core-upper', x: 1230, y: 520, width: 180, height: 22, color: 0x2f414e },
    ],
    timelineBlocks: [
      {
        id: 'past-anchor-bridge',
        x: 850,
        y: 610,
        width: 260,
        height: 22,
        states: {
          past: pastSolid,
          present: brokenPresent,
          future: gone,
        },
      },
      {
        id: 'present-anchor-lift',
        x: 1290,
        y: 560,
        width: 210,
        height: 22,
        states: {
          past: gone,
          present: presentSolid,
          future: ruinedGhost,
        },
      },
      {
        id: 'future-anchor-span',
        x: 1740,
        y: 600,
        width: 260,
        height: 22,
        states: {
          past: gone,
          present: brokenPresent,
          future: futureSolid,
        },
      },
    ],
    doors: [
      {
        id: 'keeper-barrier',
        x: 2110,
        y: 596,
        width: 68,
        height: 130,
        requiresFlags: ['anchor_past', 'anchor_present', 'anchor_future'],
        states: {
          past: { solid: true, visible: true, color: 0x584161 },
          present: { solid: true, visible: true, color: 0x274b5a },
          future: { solid: true, visible: true, color: 0x6a2836 },
        },
      },
    ],
    plates: [{ id: 'past-anchor-plate', flag: 'anchor_past', x: 410, y: 656, width: 86, height: 12, timelines: ['past'] }],
    switches: [
      { id: 'present-anchor-switch', flag: 'anchor_present', x: 1285, y: 506, width: 42, height: 34, timelines: ['present'] },
      { id: 'future-anchor-switch', flag: 'anchor_future', x: 1770, y: 644, width: 42, height: 34, timelines: ['future'] },
    ],
    enemies: [{ id: 'core-rustmite', x: 1520, y: 620, patrolMinX: 1370, patrolMaxX: 1690, speed: 90 }],
    checkpoints: [{ id: 'core-checkpoint', x: 1120, y: 620 }],
    storyZones: [
      {
        id: 'boss-plate',
        x: 340,
        y: 600,
        width: 150,
        height: 140,
        once: true,
        lines: ['Anchor one lives in the Past. Leave an echo to hold it.'],
      },
      {
        id: 'boss-present',
        x: 1220,
        y: 520,
        width: 180,
        height: 170,
        once: true,
        lines: ['Anchor two answers only to the Present.'],
      },
      {
        id: 'boss-future',
        x: 1720,
        y: 600,
        width: 170,
        height: 140,
        once: true,
        lines: ['Anchor three still stands in Ruined Future.'],
      },
      {
        id: 'keeper-reveal',
        x: 2020,
        y: 600,
        width: 160,
        height: 140,
        once: true,
        lines: ['The silhouette is too familiar. The future has been pleading in Elias\'s own voice.'],
      },
    ],
    exit: { x: 2420, y: 600, width: 70, height: 130 },
    requiredExitFlags: ['anchor_past', 'anchor_present', 'anchor_future'],
  },
];

export function getLevel(id: string): LevelData {
  const level = levels.find((candidate) => candidate.id === id);
  if (!level) {
    throw new Error(`Unknown level id: ${id}`);
  }
  return level;
}
