export const TextureKeys = {
  elias: 'character.elias',
  eliasSheet: 'character.elias-sheet',
  ghost: 'character.echo',
  keeper: 'character.keeper',
  keeperSheet: 'character.keeper-sheet',
  girl: 'character.girl',
  girlSheet: 'character.girl-sheet',
  enemy: 'character.rustmite',
  core: 'fx.chrono-core',
  particle: 'fx.time-particle',
  checkpoint: 'environment.checkpoint',
  doorSheet: 'environment.door-sheet',
  doorPast: 'environment.door-past',
  doorPresent: 'environment.door-present',
  doorFuture: 'environment.door-future',
  switchOff: 'environment.switch-off',
  switchOn: 'environment.switch-on',
  puzzleDevicesSheet: 'environment.puzzle-devices-sheet',
  plate: 'environment.pressure-plate',
  platePast: 'environment.pressure-plate-past',
  platePresent: 'environment.pressure-plate-present',
  plateFuture: 'environment.pressure-plate-future',
  exit: 'environment.exit',
  platformSheet: 'environment.platform-sheet',
  titleBackdrop: 'backdrop.title',
  backdropReactor: 'backdrop.reactor',
  backdropStreets: 'backdrop.streets',
  backdropGreenhouse: 'backdrop.greenhouse',
  backdropStation: 'backdrop.station',
  backdropCore: 'backdrop.core',
  uiSignPanel: 'ui.sign-panel',
} as const;

export const AnimationKeys = {
  eliasIdle: 'elias.idle',
  eliasWalk: 'elias.walk',
  eliasRun: 'elias.run',
  eliasJump: 'elias.jump',
  eliasFall: 'elias.fall',
  eliasTimeShift: 'elias.time-shift',
} as const;

export type TextureKey = (typeof TextureKeys)[keyof typeof TextureKeys];
export type AnimationKey = (typeof AnimationKeys)[keyof typeof AnimationKeys];
